<a href="https://colab.research.google.com/github/ABHISHEK2334/ABHISHEK-/blob/main/Iterative_Imputer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [333]:
#missing completely at random=MCAR
#missing at random= MAR
#missing not at random = MNAR

#this is use in MAR
#Multivariate Imputation by Chained Equations for Missing Value =MICE algorithm

In [334]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [335]:
df = np.round(pd.read_csv('50_Startups.csv')[['R&D Spend','Administration','Marketing Spend','Profit']]/10000)
np.random.seed(9)
df = df.sample(5)
df

R&D Spend  Administration  Marketing Spend  Profit
21        8.0            15.0             30.0    11.0
37        4.0             5.0             20.0     9.0
2        15.0            10.0             41.0    19.0
14       12.0            16.0             26.0    13.0
44        2.0            15.0              3.0     7.0

In [336]:
df = df.iloc[:,0:-1]
df

R&D Spend  Administration  Marketing Spend
21        8.0            15.0             30.0
37        4.0             5.0             20.0
2        15.0            10.0             41.0
14       12.0            16.0             26.0
44        2.0            15.0              3.0

In [337]:
df.iloc[1,0]=np.nan
df.iloc[3,1]=np.nan
df.iloc[4,2]=np.nan

<ipython-input-337-0e2688df4f44>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[1,0]=np.nan
<ipython-input-337-0e2688df4f44>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[3,1]=np.nan
<ipython-input-337-0e2688df4f44>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[4,2]=np.nan


In [338]:
df1=pd.DataFrame()
df1['R&D Spend']=df['R&D Spend'].fillna(df['R&D Spend'].mean())
df1['Administration']=df['Administration'].fillna(df['Administration'].mean())
df1['Marketing Spend']=df['Marketing Spend'].fillna(df['Marketing Spend'].mean())   #mean values
df1

R&D Spend  Administration  Marketing Spend
21       8.00           15.00            30.00
37       9.25            5.00            20.00
2       15.00           10.00            41.00
14      12.00           11.25            26.00
44       2.00           15.00            29.25

In [339]:
df2=df1.copy()
df2.iloc[1,0]=np.nan
df2

R&D Spend  Administration  Marketing Spend
21        8.0           15.00            30.00
37        NaN            5.00            20.00
2        15.0           10.00            41.00
14       12.0           11.25            26.00
44        2.0           15.00            29.25

In [340]:
x=df2.iloc[[0,2,3,4],1:3]
x

Administration  Marketing Spend
21           15.00            30.00
2            10.00            41.00
14           11.25            26.00
44           15.00            29.25

In [341]:
y=df2.iloc[[0,2,3,4],0]
y

21     8.0
2     15.0
14    12.0
44     2.0
Name: R&D Spend, dtype: float64

In [342]:
ir=LinearRegression()
ir.fit(x,y)
ir.predict(df2.iloc[1,1:].values.reshape(1,2))  #x=3

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([23.14158651])

In [343]:
df2.iloc[1,0]=23.14
df2

R&D Spend  Administration  Marketing Spend
21       8.00           15.00            30.00
37      23.14            5.00            20.00
2       15.00           10.00            41.00
14      12.00           11.25            26.00
44       2.00           15.00            29.25

In [344]:
df2.iloc[3,1]=np.nan
df2

R&D Spend  Administration  Marketing Spend
21       8.00            15.0            30.00
37      23.14             5.0            20.00
2       15.00            10.0            41.00
14      12.00             NaN            26.00
44       2.00            15.0            29.25

In [345]:
x1=df2.iloc[[0,1,2,4],[0,2]]
y1=df2.iloc[[0,1,2,4],1]
print(x1)


    R&D Spend  Marketing Spend
21       8.00            30.00
37      23.14            20.00
2       15.00            41.00
44       2.00            29.25


In [346]:
y1

21    15.0
37     5.0
2     10.0
44    15.0
Name: Administration, dtype: float64

In [347]:
ir = LinearRegression()
ir.fit(x1, y1)
ir.predict(df2.iloc[3, [0, 2]].values.reshape(1, 2))

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([11.06331285])

In [348]:
df2.iloc[3,1]=11.06

In [349]:

df2.iloc[4,2]=np.nan
df2


R&D Spend  Administration  Marketing Spend
21       8.00           15.00             30.0
37      23.14            5.00             20.0
2       15.00           10.00             41.0
14      12.00           11.06             26.0
44       2.00           15.00              NaN

In [350]:
x=df2.iloc[[0,1,2,3],[0,1]]
x

R&D Spend  Administration
21       8.00           15.00
37      23.14            5.00
2       15.00           10.00
14      12.00           11.06

In [351]:
y=df2.iloc[0:4,-1]
y

21    30.0
37    20.0
2     41.0
14    26.0
Name: Marketing Spend, dtype: float64

In [352]:
ir=LinearRegression()
ir.fit(x,y)
ir.predict(df1.iloc[4,0:2].values.reshape(1,2))


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([31.56351448])

In [353]:
df2.iloc[4,2]=31.56
df2

R&D Spend  Administration  Marketing Spend
21       8.00           15.00            30.00
37      23.14            5.00            20.00
2       15.00           10.00            41.00
14      12.00           11.06            26.00
44       2.00           15.00            31.56

In [354]:
df2-df1

R&D Spend  Administration  Marketing Spend
21       0.00            0.00             0.00
37      13.89            0.00             0.00
2        0.00            0.00             0.00
14       0.00           -0.19             0.00
44       0.00            0.00             2.31

# **repeat all step but this time base is df2 instead of df1**

In [355]:
df3=df2.copy()
df3.iloc[1,0]=np.nan
df3


R&D Spend  Administration  Marketing Spend
21        8.0           15.00            30.00
37        NaN            5.00            20.00
2        15.0           10.00            41.00
14       12.0           11.06            26.00
44        2.0           15.00            31.56

In [356]:
x = df3.iloc[[0,2,3,4],1:3]
y = df3.iloc[[0,2,3,4],0]

ir = LinearRegression()
ir.fit(x,y)
ir.predict(df3.iloc[1,1:].values.reshape(1,2))

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([23.78627207])

In [357]:
df3.iloc[1,0] = 23.78

In [358]:
df3.iloc[3,1] = np.NaN
x = df3.iloc[[0,1,2,4],[0,2]]
y = df3.iloc[[0,1,2,4],1]

ir = LinearRegression()
ir.fit(x,y)
ir.predict(df3.iloc[3,[0,2]].values.reshape(1,2))

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([11.22020174])

In [359]:
df3.iloc[3,1] = 11.22

In [360]:
df3.iloc[4,-1] = np.NaN

x = df2.iloc[0:4,0:2]
y = df2.iloc[0:4,-1]

ir = LinearRegression()
ir.fit(x,y)
ir.predict(df3.iloc[4,0:2].values.reshape(1,2))

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([31.56351448])

In [361]:

df3.iloc[4,-1] = 31.56

In [362]:
df3

R&D Spend  Administration  Marketing Spend
21       8.00           15.00            30.00
37      23.78            5.00            20.00
2       15.00           10.00            41.00
14      12.00           11.22            26.00
44       2.00           15.00            31.56

In [363]:
df3-df2

R&D Spend  Administration  Marketing Spend
21       0.00            0.00              0.0
37       0.64            0.00              0.0
2        0.00            0.00              0.0
14       0.00            0.16              0.0
44       0.00            0.00              0.0

In [364]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
import numpy as np

# Create some example data with missing values
X = np.array([[1, 2, np.nan],
              [3, np.nan, 4],
              [np.nan, 5, 6]])   #chatgpt

# Initialize IterativeImputer (MICE) with additional parameters
imputer = IterativeImputer(max_iter=10, random_state=0)

# Fit the imputer model on the data
imputer.fit(X)

# Transform the data to fill in missing values
X_imputed = imputer.transform(X)

print("Imputed Data:\n", X_imputed)


Imputed Data:
 [[1.         2.         0.86709026]
 [3.         3.83114993 4.        ]
 [4.27688157 5.         6.        ]]
